// Typed SSE handlers for the dashboard.
//
// Stream functions are generated by `@hey-api/openapi-ts` from the
// supervisor's OpenAPI spec and live in ./generated/sdk.gen. Each
// generated function uses fetch() + ReadableStream under the hood
// (not EventSource), which gives us custom headers, built-in retry,
// and per-frame dispatch via the onSseEvent callback.
//
// Runtime type guards in this file verify each frame's `data` shape
// before the consumer sees it. hey-api's generator publishes a type
// signature that does not match its runtime yield (the async
// generator yields bare `data` while the types say `Array<{event,
// data}>`), so blind casts from the frame callback into our
// DashboardEventMessage union would be unchecked. The guards below
// narrow on actual runtime shape and drop malformed frames with a
// UI error report — same discipline as the pre-migration decoder.
//
// See specs/architecture.md §6 "Tooling landscape" (TypeScript
// section) for why hey-api is the SSE tool even though openapi-fetch
// still drives REST.

import { client } from "./generated/client.gen";
import {
  streamEvents,
  streamSession,
  streamSupervisorEvents,
} from "./generated/sdk.gen";
import type {
  CityEventStreamEnvelope,
  HeartbeatEvent,
  SupervisorEventStreamEnvelope,
} from "./api";
import { reportUIError } from "./ui";

export interface SSEHandle {
  close(): void;
}

export type SSEStatus = "connecting" | "live" | "reconnecting";

export interface SSEOptions {
  onStatus?: (status: SSEStatus) => void;
}

export type HeartbeatMessage = {
  event: "heartbeat";
  id?: string;
  data: HeartbeatEvent;
};

export type CityEventMessage = {
  event: "event";
  id?: string;
  data: CityEventStreamEnvelope;
};

export type SupervisorEventMessage = {
  event: "tagged_event";
  id?: string;
  data: SupervisorEventStreamEnvelope;
};

export type DashboardEventMessage =
  | HeartbeatMessage
  | CityEventMessage
  | SupervisorEventMessage;

export interface AgentOutputMessage {
  id?: string;
  type: string;
  data: unknown;
}

// --- Runtime type guards -------------------------------------------

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function isHeartbeat(value: unknown): value is HeartbeatEvent {
  return isRecord(value) && typeof value.timestamp === "string";
}

function isBaseEventEnvelope(value: unknown): value is {
  actor: string;
  seq: number;
  ts: string;
  type: string;
} {
  return (
    isRecord(value)
    && typeof value.actor === "string"
    && typeof value.seq === "number"
    && typeof value.ts === "string"
    && typeof value.type === "string"
  );
}

function isCityEventEnvelope(value: unknown): value is CityEventStreamEnvelope {
  return isBaseEventEnvelope(value);
}

function isSupervisorEventEnvelope(value: unknown): value is SupervisorEventStreamEnvelope {
  return isBaseEventEnvelope(value) && typeof (value as { city?: unknown }).city === "string";
}

// --- Stream wrappers -----------------------------------------------

// connectEvents opens the supervisor-scope events stream
// (/v0/events/stream). Supervisor stream frames are either
// `tagged_event` (TaggedEventStreamEnvelope) or `heartbeat`
// (HeartbeatEvent). Returns an SSEHandle; close() aborts the
// underlying fetch.
export function connectEvents(
  onEvent: (msg: DashboardEventMessage) => void,
  opts?: SSEOptions,
): SSEHandle {
  const controller = new AbortController();
  opts?.onStatus?.("connecting");
  (async () => {
    try {
      const { stream } = await streamSupervisorEvents({
        client,
        signal: controller.signal,
        onSseEvent: (frame) => {
          opts?.onStatus?.("live");
          const eventName = frame.event ?? "tagged_event";
          if (eventName === "heartbeat") {
            if (!isHeartbeat(frame.data)) {
              reportUIError("Invalid supervisor heartbeat frame", frame);
              return;
            }
            onEvent({ event: "heartbeat", id: frame.id, data: frame.data });
            return;
          }
          if (eventName === "tagged_event") {
            if (!isSupervisorEventEnvelope(frame.data)) {
              reportUIError("Invalid supervisor event frame", frame);
              return;
            }
            onEvent({ event: "tagged_event", id: frame.id, data: frame.data });
            return;
          }
          reportUIError(`Unexpected supervisor SSE event: ${eventName}`, frame);
        },
      });
      // Drain the underlying async generator so the reader keeps
      // pumping frames into onSseEvent. The values it yields are not
      // used — per-frame dispatch happens in the callback above.
      for await (const _ of stream) {
        void _;
      }
    } catch (error) {
      if (!controller.signal.aborted) {
        reportUIError("Supervisor event stream failed", error);
        opts?.onStatus?.("reconnecting");
      }
    }
  })();
  return { close: () => controller.abort() };
}

// connectCityEvents opens the per-city events stream
// (/v0/city/{cityName}/events/stream). City stream frames are either
// `event` (EventStreamEnvelope) or `heartbeat` (HeartbeatEvent).
export function connectCityEvents(
  city: string,
  onEvent: (msg: DashboardEventMessage) => void,
  opts?: SSEOptions,
): SSEHandle {
  const controller = new AbortController();
  opts?.onStatus?.("connecting");
  (async () => {
    try {
      const { stream } = await streamEvents({
        client,
        path: { cityName: city },
        signal: controller.signal,
        onSseEvent: (frame) => {
          opts?.onStatus?.("live");
          const eventName = frame.event ?? "event";
          const id = frame.id !== undefined ? String(frame.id) : undefined;
          if (eventName === "heartbeat") {
            if (!isHeartbeat(frame.data)) {
              reportUIError("Invalid city heartbeat frame", frame);
              return;
            }
            onEvent({ event: "heartbeat", id, data: frame.data });
            return;
          }
          if (eventName === "event") {
            if (!isCityEventEnvelope(frame.data)) {
              reportUIError("Invalid city event frame", frame);
              return;
            }
            onEvent({ event: "event", id, data: frame.data });
            return;
          }
          reportUIError(`Unexpected city SSE event: ${eventName}`, frame);
        },
      });
      for await (const _ of stream) {
        void _;
      }
    } catch (error) {
      if (!controller.signal.aborted) {
        reportUIError("City event stream failed", error);
        opts?.onStatus?.("reconnecting");
      }
    }
  })();
  return { close: () => controller.abort() };
}

// connectAgentOutput opens the per-session transcript stream
// (/v0/city/{cityName}/session/{id}/stream). Session frames are one
// of turn, message, activity, pending, or heartbeat; the bridge
// shape collapses them into AgentOutputMessage so consumers don't
// need to discriminate by type at the transport layer. We verify
// `data` is at least a JSON value (object, array, null, primitive)
// so we never pass through garbage.
export function connectAgentOutput(
  city: string,
  sessionID: string,
  onEvent: (msg: AgentOutputMessage) => void,
): SSEHandle {
  const controller = new AbortController();
  (async () => {
    try {
      const { stream } = await streamSession({
        client,
        path: { cityName: city, id: sessionID },
        signal: controller.signal,
        onSseEvent: (frame) => {
          // Session frames carry heterogeneous typed payloads per
          // variant (SessionStreamRawMessageEvent,
          // SessionStreamMessageEvent, etc.). Consumers treat them
          // as AgentOutputMessage opaquely; the type field carries
          // the semantic event name so consumers can dispatch.
          if (frame.data === undefined) {
            reportUIError("Session frame missing data", frame);
            return;
          }
          onEvent({
            id: frame.id !== undefined ? String(frame.id) : undefined,
            type: frame.event ?? "message",
            data: frame.data,
          });
        },
      });
      for await (const _ of stream) {
        void _;
      }
    } catch (error) {
      if (!controller.signal.aborted) {
        reportUIError("Session stream failed", error);
      }
    }
  })();
  return { close: () => controller.abort() };
}

// semanticEventType returns the domain event type (e.g. "bead.created",
// "mail.sent") for an event-stream frame, falling back to "heartbeat"
// for keepalive frames.
export function semanticEventType(msg: DashboardEventMessage): string {
  if (msg.event === "heartbeat") return "heartbeat";
  return msg.data.type;
}
