"""pack.lock read/write for gc import.

Format:
    schema = 1

    [packs.<local_handle>]
    url = "https://..."
    version = "1.2.3"
    constraint = "^1.2"
    commit = "abc123..."
    hash = "sha256:..."
    parent = "gastown"      # optional; either a parent handle (transitive)
                            # or "(implicit)" for entries from the implicit list
    subpath = "foo"         # optional, present iff URL has a subpath

The reader uses tomllib (stdlib in 3.11+). The writer is hand-rolled
because we own the format and tomlkit is a third-party dep.
"""

import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


SCHEMA = 1


@dataclass
class LockedPack:
    handle: str
    url: str
    version: str
    constraint: str
    commit: str
    hash: str
    parent: Optional[str] = None
    subpath: str = ""


@dataclass
class Lockfile:
    schema: int = SCHEMA
    packs: dict[str, LockedPack] = field(default_factory=dict)

    def add(self, pack: LockedPack) -> None:
        self.packs[pack.handle] = pack

    def remove(self, handle: str) -> None:
        self.packs.pop(handle, None)

    def get(self, handle: str) -> Optional[LockedPack]:
        return self.packs.get(handle)

    def transitive_children_of(self, parent_handle: str) -> list[str]:
        return [h for h, p in self.packs.items() if p.parent == parent_handle]


def read(path: Path) -> Lockfile:
    """Read a pack.lock file. Returns an empty Lockfile if the file doesn't exist."""
    if not path.exists():
        return Lockfile()
    with open(path, "rb") as f:
        data = tomllib.load(f)
    lf = Lockfile(schema=data.get("schema", SCHEMA))
    for handle, entry in data.get("packs", {}).items():
        lf.packs[handle] = LockedPack(
            handle=handle,
            url=entry["url"],
            version=entry["version"],
            constraint=entry.get("constraint", ""),
            commit=entry["commit"],
            hash=entry.get("hash", ""),
            parent=entry.get("parent"),
            subpath=entry.get("subpath", ""),
        )
    return lf


def write(lf: Lockfile, path: Path) -> None:
    """Write a pack.lock file atomically."""
    lines = [
        "# Auto-generated by gc import. Commit for reproducibility.",
        f"schema = {lf.schema}",
        "",
    ]
    for handle in sorted(lf.packs.keys()):
        p = lf.packs[handle]
        lines.append(f"[packs.{handle}]")
        lines.append(f'url = "{p.url}"')
        lines.append(f'version = "{p.version}"')
        if p.constraint:
            lines.append(f'constraint = "{p.constraint}"')
        lines.append(f'commit = "{p.commit}"')
        if p.hash:
            lines.append(f'hash = "{p.hash}"')
        if p.parent:
            lines.append(f'parent = "{p.parent}"')
        if p.subpath:
            lines.append(f'subpath = "{p.subpath}"')
        lines.append("")
    content = "\n".join(lines)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.parent.mkdir(parents=True, exist_ok=True)
    tmp.write_text(content)
    tmp.replace(path)
